### ISSUE TITLE
readme instructions for digital property application contains errors

### ISSUE THREAD

**Issue by nklincoln** [hyperledger/composer-sample-applications#82]
Code snippets in "Hyperledger Composer Tutorial 2 - running a local application" contains errors in Step 1:

 - The file zip file retrieved cannot be unzipped
 - The tar command to unwind the tarball is missing the -f flag

**Comment by mahoney1** [comment]
Got these changes done in my local repo just now. Will do a PR in time for this repo (will look for other changes first then submit as one PR)

**Comment by EdMoffatt** [comment]
Out of curiosity, where is this tutorial?  I thought we'd re-worked our online tutorials to use the commodity trading network rather than digital property, and here's the Tutorial list from the website:
![image](https://user-images.githubusercontent.com/7454304/29508806-dd9bd21a-864d-11e7-9f18-6a0284010c66.png)

Does this one live separately on GitHub or something?  If it's content covered in the Developer Guide (https://hyperledger.github.io/composer/tutorials/developer-guide.html), should we kill the duplicates?  Or if it's content not in there, should we be rolling it into our main doc tutorials?

**Comment by mahoney1** [comment]
@EdMoffatt  yeah, its a Github 'README' tutorial for Digital Property app - in a separate sample-applications repo -> https://github.com/hyperledger/composer-sample-applications/blob/master/packages/digitalproperty-app/README.md. Its a CLI based app tutorial (as opposed to the Trade 'Developer' tutorial, which builds a generated NG2 sample app).  But yes, your thinking is right - we will create a separate CLi based tutorial to add to main docs site, as it is a different tutorial insight.  @rthatcher will be assigned this when he's back next week. Created a separate issue in main Composer (Docs) repo for this -> https://github.com/hyperledger/composer/issues/1942

**Comment by davidkel** [comment]
assume this has been fixed. As PR has been merged. Closing
